### ISSUE TITLE
探讨一下关于 attribute level component 的想法

### ISSUE THREAD

**Issue by nightire** [wppurking/ember-logs#1]
原始讨论在这里：http://discuss.emberjs.com/t/is-there-an-attribute-level-component/8763

不知你阅读英文是否习惯？大体的意思就是 Angular 的 directive 有属性级别的，有时候处理一些琐碎的 DOM／Events 相关的操作会很方便，也很对路子。但是 Ember 貌似没有，想听听你怎么看？

我举个例子，比如说我要在特定的情况下（比如说某个路由激活后，或是某个 Component 渲染后，甚至是某个 Component 中的 DOM 元素被某种事件触发后）做这样一件事情：

绑定 mousemove 事件给 `document` ，然后判定当鼠标接近浏览器左边缘的时候做某件事情（比如浮动菜单之类的）

这个倒不是说不能做，但我的感觉是很不清晰。因为你没有办法定义属性级别的 component，也就无法随心所欲把这种行为任意附着在 DOM 元素上，这样一来条件判断就很重要了，比如说这个事情可能发生在：
1. 整个应用初始化的时候
2. 某个路由激活的时候
3. 某个 component 渲染后
4. 某个 component 里的原生元素（div span 之类的）接受某种事件的时候
5. ……等等

如果有标签级别的 component 这些都不是问题，但是没有的话貌似可用的办法有很多，可又说不清楚哪种更合理一些。

你觉得呢？

@darkbaby123 你觉得呢？

**Comment by nightire** [comment]
我自己的想法是这样的：
1. 应用初始化的时候：理论上如果有 attribute component，我可以添加到 `body` 标签上；但现在没有，那么我可以在哪儿做这件事情呢？
   - `Ember.Application.init` ？
   - `ApplicationView`？
   - 未来的 `ApplicationRoutableComponent`？我希望这个，但现在做不到
2. 某个路由激活的时候：mixin 给特定路由／或者 Routable Components 连带这个一起做了
3. 某个 Component 渲染后：mixin 给特定 Component
4. 某个 component 里的原生元素（div span 之类的）接受某种事件的时候：也是 mixin 提供 action，绑定 action 给特定标签
5. 还有其他可能场景吗？

貌似 mixin 给 Component 或 Routable Component 是最合理的选择了？

**Comment by darkbaby123** [comment]
其实我反倒觉得 Angular 的 attribute directive 不算是个好主意。拿 Angular 举例子，如果一个 HTML 标签上附加多个 directive ，必然会存在多个 directive 共享一些资源或者 directive 以什么顺序执行的问题。所以 Angular directive 才有 require 和 priority 的设定。虽然我也挺习惯这样的方案，但总觉得有点复杂了。如果 Ember component 弄成这样，也必须考虑以上的两个问题。

Ember 的 component 就是类似 web component 的东西，一个 component 当做一个 HTML 标签用。限制其实比 Angular directive 大，但有限制反而把事情变得更清晰，就如无状态的 HTTP 之于 TCP 。

到你具体的例子，可能我没理解你的意思。如果拿浮动菜单来说，我会建一个 Ember component 表示浮动菜单，然后加入 `application.hbs` 里，component 里面处理怎么给 document 或 window 绑定和解绑事件。

如果是一些公用的 component 逻辑，比如 “鼠标点击页面空白处就 XXX” ，那我会写一个 mixin，鼠标点击空白处发送一个事件。component（如 modal 和 dropdown ）可以混入 mixin ，实现对应的事件就行。这种方式有个弱点，如果想附加功能给一些 HTML 标签就不行了，必须写 component 代替原生 HTML 标签。不过我觉得这样很合理，给原生 HTML 标签附加功能，不如抽象一个 component 去处理。

**Comment by nightire** [comment]
@darkbaby123 嗯，我思来想去，如果不搞什么 Attribute Component，那的确如你所说：必要的时候就是要创建 component 去代替原生 HTML。

一开始会纠结这个问题就是在转换一些 Angular Directive 到 Ember Component 的时候，发现有很多东西在 Angular 里都依赖了 attribute directive，这样一来特别复杂的 HTML 结构在 Angular 里没有必要搞很多 Element 级别的 directives，感觉会比较简洁清晰。反过来在 Ember 里则可能要定义大量的 Components 来处理一些特别琐碎的 DOM／Event 处理。

先试试吧，等到 Components 量上去了大概会梳理清楚组织的思路，反正以前写很多 Directives 的时候也是会有类似的问题。

**Comment by wppurking** [comment]
对 Angular 理解有限 - -|| 所以就从问题的场景来理解了.

"特定条件下动态的给某个元素绑定特定的事件"   (不知道我这样理解是不是正确)

如果我有这样场景的问题, 在 Ember 中我会有这样的思路:
1. 特定条件抽象到 Mixin 中, 并且是否满足的判断以及相关涉及的判断接口或者字段封装到一起.
2. 为有这种需要的 Component 引入这个 Mixin
3. 在 Comonent 自己的代码中来控制 Mixin 的"开"/"关"

这个和 @darkbaby123 的应该比较类似.  是没办法为某些 <标签> 元素以添加 "属性" 的方式开启关闭功能特性, 得在 Component 里面 Mixin 进这个特性进来加以控制.

我比较倾向 Component 事情专一的事情, 把 Ember 中的一个一个的 Component 理解成为 HTML 中的 <vedio> 标签这样的级别就好. 是他的事情, 他自己处理了, 不是他的事情要么扩展他要么 Mixin.

题外话: 
1. 我发现我关了项目的 issue Email 提醒了... 刚刚看到.
2. 我建议哈, 如果讨论有个结论, 觉得最后拥有一个最后的结论, 这样至少给一个讨论有个终结点.

**Comment by darkbaby123** [comment]
我比较支持 component 专一的做法，有些限制可以让代码变得更好维护，因为更简单。 实际上我在用 Ember 时几乎没什么情况需要用到类似 Angular 的属性或者 class directive 。

如果说缺陷，就是写 JS 代码会比 Angular 那种方式要多。但代码意图更明确，我觉得这还是值得的。

**Comment by nightire** [comment]
@wppurking 我的最后结论（目前为止的）已经整理成文写在 [Ruby China 上了](https://ruby-china.org/topics/27359)，两位的建议都很宝贵，受益匪浅，多谢多谢！
