### ISSUE TITLE
ember-cli 前端如何处理权限以及验证的问题?

### ISSUE THREAD

**Issue by wppurking** [wppurking/ember-logs#17]
如果需要很多部分进行合作处理, 并且在参考了多个建立在 Ember 1.x 版本中的例子[ember-simple-auth](https://github.com/simplabs/ember-simple-auth) 以及 [torii](https://github.com/vestorly/torii). 下面是主要的思路:
1. 需要使用 Service 在多个不同的上下文 Context 中共享一些用户登陆的信息, 并且需要自己处理用户体验方面的功能.
2. 在 template 中需要使用到重复字段的时候, 需要使用到 Ember.Mixin. Ember 中专门用于共享页面上下文字段功能
3. 根据所需要的功能, 将 Ember.Mixin 引入到 Router(在 beforeModel 中拦截请求) , Controller(在各种 Controller 里面共享变量) 上, 为需要进行验证的 Route 与 Controller 添加特性.
#### [90%]注意几个点
1. 与前端登陆/登陆/用户/错误信息等的完整一套在 service 中全部处理.
2. 利用 mixin 将 service 中需要共享给 Router 与 Controller 的字段全部共享出去.
3. 思考, 在 Ember 2.1 中没有 Controller 了使用 [Routable Components](https://github.com/emberjs/rfcs/pull/38) 该如何处理?

**Comment by nightire** [comment]
@wppurking Routable Components 还是 Components，只是一种具有路由管理的特别的组件罢了，所以不出意外的话 service 照常使用，且不需要 Controller 做模版之前的控制层了，架构上应该是被“瘦身”了。
