### ISSUE TITLE
加速客户的访问 CDN

### ISSUE THREAD

**Issue by wppurking** [wppurking/ember-logs#25]
无论是什么网站, 加速网站的内容到客户端点的速度都是一个非常重要的话题.

对于一个 SPA + API Server 的项目来说, 有两块需要进行控制
- API Server 的处理性能.  这部分的处理速度
  - 加快 API Server 的请求接入响应速度 [接受到第一个 byte 的响应时间]
    - 去除了耗时的 Server View Render
    - 控制业务代码后端 DB 的处理速度
    - 服务端 Cache 计算返回
  - 减少服务器给到客户端的数据内容
    - 客户端缓存 [Etag, LastModifyTime]
- SPA 数据的加载速度
  - 压缩无用的空格数据, Gzip
  - 扩宽客户端下载数据的带宽

在一个对比试验中, 使用 七牛的 CDN 与不适用七牛的 CDN 来访问 ember-rc.daoapp.io 这个应用, 他们的差距为:

使用七牛:  207ms
![image](https://cloud.githubusercontent.com/assets/448364/9897783/0506c5c6-5c7f-11e5-9f77-cfcf2e34ab34.png)

使用daoapp:  4810ms (4.81s)
![image](https://cloud.githubusercontent.com/assets/448364/9897786/0b2e94ce-5c7f-11e5-9de9-c20c538654f2.png)

这个差距是相当明显的(23 倍) , 这个在用户的体验上是巨大的!  在使用七牛 CDN 后基本不用怎么等待就可以直接打开 ember-rc 的 app 直接开始抓取 API Server 的数据.

**Comment by nightire** [comment]
所以说七牛挺不错的咯？你推荐不？

**Comment by wppurking** [comment]
@nightire 我在湖南长沙这个地区测试, 无论在公司,家里还是手机上的网络, 七牛的 CDN 网络速度都挺快的, 特别是 [TTFB](https://www.google.com/#hl=en&newwindow=1&qscrl=1&sclient=psy-ab&q=ttfb&oq=ttfb) 的阶段, 过了 TTFB 的 Download 阶段在国内各大 CDN 在带宽下载方面都不用太担心. 

我现在自己在用 upyun, 因为综合效果, 费用, 项目工程因素比起来, 还是 upyun 对我来得实在. TTFB 速度虽慢点(快 100ms 左右, 慢 1 s), 因为 Ember 是一次性下载的, 所以也可以接受, 总体效果还是可以控制住. 

七牛 CDN 是综合各大现有 CDN 的"分销商", 还是有他的优势, 那速度真的是很快. 可是那价格..... 

(100TB 以上我现在肯定达不到)
- HTTP CDN:  0.45~0.5  / 0.29  (七牛/又拍云: 1.5 倍)
- HTTPS CDN: 0.9~1.0 / 0.29 (七牛/又拍云: 3.1 倍)  - -||

我现在是纯 HTTPS CDN

另外七牛 CDN 的优势会自动更新同名文件的 js 的缓存, 这个效果在使用 ember-cli 为 js/css 文件加上了 md5 摘要指纹后就没意义了.

**Comment by nightire** [comment]
原来如此，以前对 CDN 供应商没什么研究，你这么一说心里清楚了好多，多谢。

发件人: wppurking notifications@github.com
回复: wppurking/ember-logs reply@reply.github.com>
日期: 2015年9月19日 at 上午10:13:35
到: wppurking/ember-logs ember-logs@noreply.github.com>
抄送: Yu Albert dev.yufan@gmail.com>
邮件标题:  Re: [ember-logs] 加速客户的访问 CDN (#25)  

@nightire 我在湖南长沙这个地区测试, 无论在公司,家里还是手机上的网络, 七牛的 CDN 网络速度都挺快的, 特别是 TTFB 的阶段, 过了 TTFB 的 Download 阶段在国内各大 CDN 在带宽下载方面都不用太担心.

我现在自己在用 upyun, 因为综合效果, 费用, 项目工程因素比起来, 还是 upyun 对我来得实在. TTFB 速度虽慢点(快 100ms 左右, 慢 1 s), 因为 Ember 是一次性下载的, 所以也可以接受, 总体效果还是可以控制住.

七牛 CDN 是综合各大现有 CDN 的"分销商", 还是有他的优势, 那速度真的是很快. 可是那价格.....

(100TB 以上我现在肯定达不到)

HTTP CDN: 0.45~0.5 / 0.29 (七牛/又拍云: 1.5 倍)
HTTPS CDN: 0.9~1.0 / 0.29 (七牛/又拍云: 3.1 倍) - -||
我现在是纯 HTTPS CDN

另外七牛 CDN 的优势会自动更新同名文件的 js 的缓存, 这个效果在使用 ember-cli 为 js/css 文件加上了 md5 摘要指纹后就没意义了.
