### ISSUE TITLE
初始化的时候报找不到cookies.min.js

### ISSUE THREAD

**Issue by zachzhao1984** [wppurking/ember-logs#26]

**Comment by wppurking** [comment]
参见 #15 以及 [ember-rc](https://github.com/wppurking/ember-rc/blob/master/ember-cli-build.js#L40) 中引入 moment.js 的情况.

**Comment by zachzhao1984** [comment]
the situation is like this. seems missing some package or package content is changed.
<img width="744" alt="screen shot 2015-09-22 at 10 17 06 am" src="https://cloud.githubusercontent.com/assets/445029/10009666/28acf6ec-6113-11e5-98c4-b9af7295854d.png">

**Comment by wppurking** [comment]
1. 现在 ember-cli 已经 1.3.x 了, 可以升级了. 
2. 你 cookies.min.js 是通过 bower 安装吗? 需要保证 bower_components 目录里面有你的文件. 
3. 不要拿这个项目当例子 - -|| 这个项目是用来记录一些信息的.  你可以拿 [ember-rc](https://github.com/wppurking/ember-rc) 来当例子, 这是一个完整的项目.

另外, 这个属于个人使用上的问题, 所以还是需要多尝试, 多看一下[官方的文档](http://www.ember-cli.com/user-guide/), 多尝试一下自己找方法.

**Comment by zachzhao1984** [comment]
恩，谢谢了，通读这个repo解决了我不少实际项目里的初始问题
