### ISSUE TITLE
ember 中的 test 如何确定编写 Acceptance Test 还是 Integration Test

### ISSUE THREAD

**Issue by wppurking** [wppurking/ember-logs#29]
在经历过给 ember-rc 编写一次测试后, 感觉在编写 test 的时候, 如果需要测试的无论是 integration test 还是 unit test , 只要等待测试的组件涉及到的其他依赖一多, 就会卡壳.
1. intergration test 中测试 Component, 如果这个 Component 里面使用了其他的 Component 的话, 我就跑不下去, 因为不知道应该在哪里将其他依赖的 Component 引入. (使用 needs 将会变为 unit test, 同时还无效)
2. intergration test 中测试 Component (unit 测试的 Controller/Component 一样), 如果这个 Component 中使用类似 `application.inject('component', 'utils', 'service:utils-service');`  注册到 Component 的方法, 现在也不知道该如何在测试代码中将这个 Service 注入.(不要想直接 stub, 复杂 Service 处理起来就太不现实了)

另外: 也要想清楚:
- Model 我要测什么? 
- Router 我要测什么?
- Component 我要测什么?
- Service 我要测什么?

明确以后, 再根据场景落地到具体是 Integration test 还是 unit test (Acceptance Test 就直接测试功能了与这种组件级别无关了).

**Comment by wppurking** [comment]
补充一篇文章: [Integration and Acceptance Testing with Ember.js](http://blogs.visoftinc.com/2015/04/22/integration-acceptance-testing-emberjs/)

[ ember-metrics](https://github.com/poteto/ember-metrics/blob/develop/tests/unit/services/metrics-test.js) 是一个参考 test 的很好的例子

**Comment by wppurking** [comment]
记录一些测试的工具:

stub/mock 的工具: [sinon](https://github.com/sinonjs/sinon)

**Comment by nightire** [comment]
你引用的文章看起来很新，等有时间看看去。简单说说我的想法：

集成测试不等于验收测试，反之亦然。其实二者是不同层面上的测试，不具备可比性。

验收测试（Acceptance Test）在我看来其实很简单，作为编写测试的人完全不要考虑代码逻辑是什么，而是考虑用户使用的场景和交互过程。它通常测试如下内容：
- 路由转换：通过判断转换前后的 url／path／页面元素等的变化
- UI 呈现：不需要考虑 UI 组件是不是 Components 或是哪些 Components，而是直接判断最终的 DOM 是否正确，比如有没有对应的 content／class／style……，数量对不对，位置对不对等等
- 交互结果：通过模拟点击／填充／选择……然后判断 UI 上的变化是否符合需求的预期

所以，验收测试其实就是把自己当成用户来测试应用是否能符合我的需求而完全不要考虑代码逻辑是什么或者实现逻辑是什么，不去判断代码与实现逻辑，只判断应用的表现是否符合业务逻辑即可。

集成测试一开始也让我觉得有点搞，我一直以为 `this` 是 Component 实例的引用，后来才意识到这其实是渲染 Component 的作用域的实例，可以视作一个刚好够渲染 Component(s) 的微型 Ember App。

我也一直在想如果我要测试嵌套组件，该如何 import 其他的组件？

后来才明白，你不需要 import，因为 `this` 就是一个 app，`this.render(hbs`...`)` 就当 template.hbs 去写，想怎么嵌套就怎么嵌套。当测试运行时，这个微型 Ember App 里的 container 会根据你写的 htmlbars helper 自己去 lookup Component Instances。我们可以用 `this.set` 设定渲染前环境内可访问的数据，然后传递给 Components（通过 htmlbars helpers）。最终的 expectations 其实和 acceptance tests 的方式很类似，靠判断渲染后的实际 DOM 表现而定。

但我现在没想明白的是组件封装的交互操作如何测试？要把 Acceptance Tests 里面的那些 helpers import 进来？可以吗？

还有 Components Class 内部的逻辑，它们不应该属于集成测试了，而是单元测试。现在默认生成的是集成测试（以前是单元测试），但是再加一份单元测试也不难。

**Comment by nightire** [comment]
BTW: http://discuss.emberjs.com/t/service-injection-in-component-integration-tests/8956

**Comment by wppurking** [comment]
- 验收测试的范围比较容易理解, 是以用户为出发点来测试应用的输入与输出.
- 开始比较绕脑在集成测试上, 看你上面一说然后再找了一些[资料](https://msdn.microsoft.com/zh-tw/library/dn168871.aspx?f=255&MSPPError=-2147217396), 也能理解了, 这个的作用范围再细一级, 到组件上, 或者说是一系列小功能组成的大的黑箱子的测试, 是面向这个黑箱子的测试. 
- 最后就是单元测试了, 这个就没啥歧义了. 

总结下: 
单元测试: 独立方法级别
集成测试: 测试组件级别, 相关方法合作完成的组件.
验收测试: 面向用户, 测试应用级别

---

另外关于在集成测试中测试 Component 的一个例子:
![qq20151015-3](https://cloud.githubusercontent.com/assets/448364/10510741/4f018ce8-7367-11e5-9740-2825281f7727.png)

我测试的是 {{noty-item}}, 在 {{noty-item}} 中使用了 {{time-in-words}} helper 与 {{mark-down}} helper, 同时 {{time-in-words}} 中引入了三方库 momnet.js , 在 helper/time-in-helper.js 的测试中是通过, 但 noty-item 的测试却失败.

依赖关系: 
noty-item [ component ]
- time-in-words [ helper ]
  - moment.js [ js ]
- mark-down [ helper ]
  - marked [ js ]

另外, 我也尝试了一下在 Component 里面仅仅嵌套一个 Component, 看效果是自己去寻找了额外的 Component. 我翻了一下 [ember test](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/test.js) 的代码 [ember-testing](https://github.com/emberjs/ember.js/tree/master/packages/ember-testing/lib) 由于我还没看懂 ember 整个项目的启动流程是什么样的, 所以这里我还说不清, 只能猜测的确是解析到了正确的嵌套 Component, 但不解的是上面的那种情况. (从错误信息来看, 的确是有进入寻找.)

helper/time-in-helper.js 已经正常解析通过了, 为什么 {{noty-item}} 这个 Component 却失败了呢?

---

在 Acceptance Tests 中的那些 helper 是在 [ember-testing](https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers.js) 中实现的, 查到 ember.js 中的代码, 倒是可以通过插入, 但还没试验...
![qq20151015-4](https://cloud.githubusercontent.com/assets/448364/10511612/125c73b0-736d-11e5-98da-247c5e7872c5.png)
