### ISSUE TITLE
ember-cli server 中编译文件现在是全部重新编译, 项目越大文件越多会越慢?

### ISSUE THREAD

**Issue by wppurking** [wppurking/ember-logs#7]
这个暂时在使用 ember-cli 的时候没有办法解决, 不过好在 ember-cli 在来临的 v1.0.0 版本着手解决这个问题了, 见 [issue 2371](https://github.com/ember-cli/ember-cli/issues/2371), 所以这个什么都不用做, 等着 ember-cli 社区完成后对 ember-cli 更新即可.

**Comment by nightire** [comment]
话说你现在一个项目本地改动之后要 build 多久？

我不久前升级了 1.13.13，速度快了好多，在有 watchman 的时候，改动后构建在 2s 左右，已经可以忍受了……

**Comment by zachzhao1984** [comment]
我们组有个用windows开发的，build慢到简直难以忍受

**Comment by wppurking** [comment]
现在这个问题在 JavaScript 代码上基本上木有了.

在 broccoli 方面解决的, 然后在 [这个 pull request 里面解决了](https://github.com/broccolijs/broccoli-merge-trees/pull/31), windows 也是被考虑的.   然而 ember-cli 直接引用库问题 - -||

同时他们还有一个[好大巴大的重复代码项目](https://github.com/ember-cli/stress-app)来测试 rebuild 的速度. (超级详细的解释)

接着他们开始进行 [CSS 代码方面的加速了](https://github.com/ember-cli/ember-cli/pull/5165)

最近这些版本, ember team 都在提升工具的性能, 看着 Glimer 引擎都被 Yehuda 在用 TypeScript 写 v2, 看着 ember 一块一块重要功能都被模块化了.

@nouh 赶紧让他们组更新 ember-cli 到 1.13.13 (虽然在 [1.13.9](https://twitter.com/stefanpenner/status/664532283412484096) 就更新了, 但与 npm 之间有些问题)

@nightire 最近在处理一些后端的日志和安全的问题 - -|| 还没抽出时间来看前端. 所以只是在跟进一些变化还没应用上 :smile_cat: 

补充四个相关项目:
 https://github.com/broccolijs/broccoli-merge-trees
 https://github.com/broccolijs/broccoli-funnel
 https://github.com/broccolijs/broccoli-filter
 https://github.com/broccolijs/broccoli-persistent-filter

**Comment by nightire** [comment]
@wppurking CSS hot reload 以前是一个 addon，我用过但是兼容性问题不少，pods 结构用着用着就失灵了，这次合并到 ember cli 里，质量会有保障啦。

**Comment by zachzhao1984** [comment]
升级到ember-cli到1.13.13了，不过启动ember s的时候版本号还是1.13.8. 估计是他们版本号忘记改了吧

**Comment by nightire** [comment]
@nouh 不对，你的升级怕是有问题，这个版本号应该是正确的。

**Comment by wppurking** [comment]
@nouh [v1.13.13](https://github.com/ember-cli/ember-cli/releases/tag/v1.13.13) 如果不懂自己哪里没弄好, 建议从里面的 `Setup` 到 `Project Update` 走完.

**Comment by zachzhao1984** [comment]
谢谢两位, @wppurking 按照说明已升级好，感觉快了挺多
